apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: alpine_telegraf
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - /srcs/livenessprobe.sh
          initialDelaySeconds: 5
          periodSeconds: 3
        ports:
        - containerPort: 8125
        volumeMounts:
        - name: telegraf-endpoint
          mountPath: "/var/run/docker.sock"
      volumes:
      - name: telegraf-endpoint
        hostPath:
          path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
spec:
  type: ClusterIP
  ports:
  - name: telegraf
    port: 8125
    targetPort: 8125
    protocol: TCP
  selector:
    app: telegraf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: telegraf-account
  labels:
    app: telegraf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegraf-role
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: telegraf-account
  namespace: default